/** @type {import('tailwindcss').Config} */
export default {
        darkMode: "class",
        content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
          extend: {
            "colors": {
                    "warning-spam": "#EF4444",
                    "primary-container": "#0a0b14",
                    "primary": "#c6c5d2",
                    "surface-variant": "#26364a",
                    "surface-container-low": "#0b1c30",
                    "on-secondary-fixed-variant": "#3c475a",
                    "inverse-surface": "#d3e4fe",
                    "surface": "#031427",
                    "on-primary-fixed": "#1a1b24",
                    "background": "#031427",
                    "on-tertiary-container": "#857866",
                    "surface-container": "#102034",
                    "primary-fixed-dim": "#c6c5d2",
                    "on-secondary-container": "#aeb9d0",
                    "tertiary-container": "#110a02",
                    "surface-light": "#DCFCE7",
                    "primary-fixed": "#e3e1ef",
                    "tertiary-fixed-dim": "#d4c4b0",
                    "on-secondary": "#263143",
                    "surface-container-lowest": "#000f21",
                    "secondary": "#bcc7de",
                    "on-error-container": "#ffdad6",
                    "on-tertiary": "#392f21",
                    "error-container": "#93000a",
                    "inverse-on-surface": "#213145",
                    "on-surface-variant": "#c8c5cc",
                    "on-background": "#d3e4fe",
                    "tertiary-fixed": "#f1e0cb",
                    "surface-container-highest": "#26364a",
                    "success-ham": "#22C55E",
                    "surface-bright": "#2a3a4f",
                    "on-tertiary-fixed": "#231a0d",
                    "outline": "#919096",
                    "on-secondary-fixed": "#111c2d",
                    "outline-variant": "#47464b",
                    "surface-dim": "#031427",
                    "inverse-primary": "#5d5d69",
                    "surface-tint": "#c6c5d2",
                    "secondary-fixed": "#d8e3fb",
                    "on-tertiary-fixed-variant": "#504536",
                    "on-primary-container": "#797985",
                    "surface-container-high": "#1b2b3f",
                    "secondary-container": "#3e495d",
                    "on-surface": "#d3e4fe",
                    "on-error": "#690005",
                    "on-primary": "#2f303a",
                    "on-primary-fixed-variant": "#454651",
                    "error": "#ffb4ab",
                    "secondary-fixed-dim": "#bcc7de",
                    "white": "#FFFFFF",
                    "tertiary": "#d4c4b0"
            },
            "borderRadius": {
                    "DEFAULT": "0.125rem",
                    "lg": "0.25rem",
                    "xl": "0.5rem",
                    "full": "0.75rem"
            },
            "spacing": {
                    "margin-desktop": "64px",
                    "unit": "4px",
                    "margin-mobile": "16px",
                    "gutter": "24px",
                    "container-max": "1440px"
            },
            "fontFamily": {
                    "body-sm": ["Nunito", "sans-serif"],
                    "label-mono": ["Nunito", "sans-serif"],
                    "body-md": ["Nunito", "sans-serif"],
                    "headline-lg-mobile": ["Nunito", "sans-serif"],
                    "headline-xl": ["Nunito", "sans-serif"],
                    "headline-lg": ["Nunito", "sans-serif"]
            },
            "fontSize": {
                    "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                    "label-mono": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
                    "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                    "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                    "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}]
            }
          },
        },
      }
